"""Claude Code transcript JSONL 流式解析器。纯函数,不碰数据库、不碰全局状态。

事实依据(本机 CLI 2.1.228 实测,详见 ~/.claude/plans/ultrathink-claudecode-glittery-minsky.md):
- 每行一个 JSON 对象,分两类:控制行(无 uuid,如 ai-title/last-prompt/mode)与消息行(带 uuid)。
- 单行实测最长 1.45MB;缓冲上限取 8MB,超限行整行丢弃并计数。
- 文件由 Claude Code 并发追加:末尾不以 \n 结尾的半行绝不消费,
  解析偏移永远停在最后一个完整行边界,下一轮再读。
- resume/后台扫描只会追加无 timestamp 的控制行 → last_ts 不能用文件 mtime,
  必须取最后一条带顶层 timestamp 的行。
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import BinaryIO

MAX_LINE_BYTES = 8 * 1024 * 1024
MAX_TEXT_CHARS = 200_000  # 单条可搜文本上限(超大粘贴截断)

_CAVEAT_RE = re.compile(
    r"(?s)Caveat: The messages below were generated by the user.*?"
    r"unless the user explicitly asks you to\.?"
)
_TAG_RE = re.compile(r"(?s)<[^<>\n]{1,120}>")
_WS_RE = re.compile(r"\s+")


@dataclass
class TextRow:
    """一条进入搜索索引的文本。seq 为文件内所有带 uuid 行的序号(渲染层同规则编号)。"""

    seq: int
    uuid: str | None
    ts: str | None
    kind: str  # 'user_text' | 'assistant_text'
    text: str
    byte_offset: int | None = None  # 该行在文件中的起始字节,详情页可 seek 直达


@dataclass
class ChunkResult:
    """从某个字节偏移解析到文件当前末尾(或半行边界)的累计结果。"""

    new_offset: int
    seq_end: int
    rows: list[TextRow] = field(default_factory=list)
    msg_count: int = 0
    bad_lines: int = 0
    # 会话元数据(None = 本段没见到;由 indexer 与既有值合并)
    cwd: str | None = None
    slug: str | None = None
    version: str | None = None
    git_branch: str | None = None
    bridge_session_id: str | None = None
    ai_title: str | None = None
    last_prompt: str | None = None
    first_user_text: str | None = None
    first_ts: str | None = None
    last_ts: str | None = None
    has_compact: bool = False
    in_tokens: int = 0
    out_tokens: int = 0
    cache_read_tokens: int = 0
    cache_write_tokens: int = 0
    # 按日 usage(键=YYYY-MM-DD,值=[in, out, cache_read, cache_write]),供用量曲线
    usage_daily: dict[str, list[int]] = field(default_factory=dict)
    # 按小时 usage(键=YYYY-MM-DDTHH,UTC),供 5h 配额窗口
    usage_hourly: dict[str, list[int]] = field(default_factory=dict)


def clean_user_title(text: str, limit: int = 80) -> str:
    """从用户消息原文提炼列表标题:去 Caveat 样板与伪 XML 标签,压空白,截断。"""
    t = _CAVEAT_RE.sub(" ", text)
    t = _TAG_RE.sub(" ", t)
    t = _WS_RE.sub(" ", t).strip()
    return t[:limit]


def parse_chunk(
    fp: BinaryIO,
    *,
    start_offset: int = 0,
    start_seq: int = 0,
    max_line_bytes: int = MAX_LINE_BYTES,
    max_text_chars: int = MAX_TEXT_CHARS,
) -> ChunkResult:
    """从 start_offset 流式解析到文件末尾。

    返回的 new_offset 永远指向最后一个被完整消费的行之后(半行安全);
    seq 只对带 uuid 的行递增,与渲染层共用同一编号规则。
    """
    res = ChunkResult(new_offset=start_offset, seq_end=start_seq)
    seq = start_seq

    for kind, line_start, d, offset in iter_jsonl(
        fp, start_offset=start_offset, max_line_bytes=max_line_bytes
    ):
        if kind != "obj":
            if kind == "bad":
                res.bad_lines += 1
            res.new_offset = offset
            continue

        if "uuid" in d:
            _handle_message_line(d, seq, line_start, res, max_text_chars)
            seq += 1
        else:
            _handle_control_line(d, res)

        ts = d.get("timestamp")
        if isinstance(ts, str) and ts:
            if res.first_ts is None:
                res.first_ts = ts
            res.last_ts = ts

        res.new_offset = offset

    res.seq_end = seq
    return res


def iter_jsonl(fp: BinaryIO, *, start_offset: int = 0, max_line_bytes: int = MAX_LINE_BYTES):
    """流式产出完整行:(kind, line_start, obj, offset_after)。

    kind ∈ 'obj'(合法 JSON dict) | 'bad'(坏行/超长行/非 dict) | 'blank'(空行)。
    半行(文件正在被写)与写入中的超长行处自然终止,绝不消费;
    调用方以最后一次产出的 offset_after 作为下一轮解析起点。
    Claude 与 Codex 两种 JSONL 共用这一套行框架纪律。
    """
    fp.seek(start_offset)
    offset = start_offset
    while True:
        line_start = offset
        line = fp.readline(max_line_bytes)
        if not line:
            return
        offset += len(line)

        if not line.endswith(b"\n"):
            if len(line) >= max_line_bytes:
                # 超长行:吞到下一个换行;若到 EOF 仍无换行(还在写),整段不消费
                consumed = _discard_to_newline(fp, max_line_bytes)
                if consumed is None:
                    return
                offset += consumed
                yield "bad", line_start, None, offset
                continue
            # 尾部半行:写入方还没收笔,下一轮再读
            return

        stripped = line.strip()
        if not stripped:
            yield "blank", line_start, None, offset
            continue

        try:
            d = json.loads(stripped)
        except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
            yield "bad", line_start, None, offset
            continue
        if not isinstance(d, dict):
            yield "bad", line_start, None, offset
            continue
        yield "obj", line_start, d, offset


def _discard_to_newline(fp: BinaryIO, max_line_bytes: int) -> int | None:
    """超长行丢弃模式:读到下一个 \n 为止,返回消费字节数;EOF 无换行返回 None。"""
    consumed = 0
    while True:
        part = fp.readline(max_line_bytes)
        if not part:
            return None
        consumed += len(part)
        if part.endswith(b"\n"):
            return consumed


def _handle_message_line(
    d: dict, seq: int, line_start: int, res: ChunkResult, max_text_chars: int
) -> None:
    if res.cwd is None and isinstance(d.get("cwd"), str):
        res.cwd = d["cwd"]
    for src, dst in (("slug", "slug"), ("version", "version"), ("gitBranch", "git_branch")):
        v = d.get(src)
        if isinstance(v, str) and v:
            setattr(res, dst, v)

    mtype = d.get("type")
    msg = d.get("message")
    if not isinstance(msg, dict):
        msg = {}

    if mtype == "user":
        res.msg_count += 1
        texts: list[str] = []
        content = msg.get("content")
        if isinstance(content, str):
            if not d.get("isCompactSummary") and not content.lstrip().startswith("<command-"):
                texts.append(content)
        elif isinstance(content, list):
            for block in content:
                if (
                    isinstance(block, dict)
                    and block.get("type") == "text"
                    and isinstance(block.get("text"), str)
                ):
                    texts.append(block["text"])
        for raw in texts:
            txt = raw.strip()
            if not txt:
                continue
            res.rows.append(
                TextRow(
                    seq,
                    d.get("uuid"),
                    d.get("timestamp"),
                    "user_text",
                    txt[:max_text_chars],
                    line_start,
                )
            )
            if res.first_user_text is None:
                cand = clean_user_title(txt)
                if cand:
                    res.first_user_text = cand

    elif mtype == "assistant":
        res.msg_count += 1
        parts: list[str] = []
        content = msg.get("content")
        if isinstance(content, list):
            for block in content:
                if (
                    isinstance(block, dict)
                    and block.get("type") == "text"
                    and isinstance(block.get("text"), str)
                ):
                    parts.append(block["text"])
        if parts:
            joined = "\n\n".join(parts).strip()
            if joined:
                res.rows.append(
                    TextRow(
                        seq,
                        d.get("uuid"),
                        d.get("timestamp"),
                        "assistant_text",
                        joined[:max_text_chars],
                        line_start,
                    )
                )
        usage = msg.get("usage")
        if isinstance(usage, dict):
            vals = (
                _as_int(usage.get("input_tokens")),
                _as_int(usage.get("output_tokens")),
                _as_int(usage.get("cache_read_input_tokens")),
                _as_int(usage.get("cache_creation_input_tokens")),
            )
            res.in_tokens += vals[0]
            res.out_tokens += vals[1]
            res.cache_read_tokens += vals[2]
            res.cache_write_tokens += vals[3]
            ts = d.get("timestamp")
            if isinstance(ts, str) and len(ts) >= 10:
                day = res.usage_daily.setdefault(ts[:10], [0, 0, 0, 0])
                for i in range(4):
                    day[i] += vals[i]
                if len(ts) >= 13:
                    hour = res.usage_hourly.setdefault(ts[:13], [0, 0, 0, 0])
                    for i in range(4):
                        hour[i] += vals[i]

    elif mtype == "system":
        if d.get("subtype") == "compact_boundary":
            res.has_compact = True
    # attachment 行:不提取文本


def _handle_control_line(d: dict, res: ChunkResult) -> None:
    ctype = d.get("type")
    if ctype == "ai-title":
        v = d.get("aiTitle")
        if isinstance(v, str) and v.strip():
            res.ai_title = v.strip()  # 同文件重复追加,取最后一条
    elif ctype == "last-prompt":
        v = d.get("lastPrompt")
        if isinstance(v, str) and v.strip():
            res.last_prompt = v.strip()
    elif ctype == "bridge-session":
        v = d.get("bridgeSessionId")
        if isinstance(v, str) and v:
            res.bridge_session_id = v
    # mode / permission-mode / file-history-* / agent-name / queue-operation /
    # fork-context-ref / frame-link 等控制行:忽略


def _as_int(v: object) -> int:
    try:
        return int(v)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return 0


def bridge_url(bridge_session_id: str | None) -> str | None:
    """cse_<ULID> 与 session_<ULID> 同体仅前缀不同;网页地址用 session_ 前缀。"""
    if not bridge_session_id:
        return None
    body = bridge_session_id
    for prefix in ("cse_", "session_"):
        if body.startswith(prefix):
            body = body[len(prefix):]
            break
    return f"https://claude.ai/code/session_{body}"
